# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile.contrast'
        arguments: '-t webgoatdotnetcorewcontrast'
- stage: Run
  displayName: Run container
  jobs:
  - job: Run
    displayName: Run
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Run a container
      inputs:
        command: start
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile.contrast'
        arguments: 'webgoatdotnetcorewcontrast'
- stage: Verify
  jobs:
  - job: Verify
    pool: server
    steps: 
    - task: ContrastIntegration@2
      inputs:
        ContrastService: 'Contrast AppTwo'
        Application: '53c9d540-2cee-40a0-8a57-0552f8b917de'
        AppVersionFilter: '$(Build.BuildId)_$(Build.BuildNumber)'
        CriticalLimit: '0'
        HighLimit: '0'
        MediumLimit: '-1'
        LowLimit: '-1'
        NoteLimit: '-1'